dbfilename redis_queue.rdb
dir /workspaces/mips-erpnext/mips-prod/config/pids
pidfile /workspaces/mips-erpnext/mips-prod/config/pids/redis_queue.pid
bind 127.0.0.1
port 11001

aclfile /workspaces/mips-erpnext/mips-prod/config/redis_queue.acl
